[package]
name = "aware"
version = "0.0.11"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/imp/aware-rs"
description = "AWS Resource Explorer"

[dependencies]
anyhow = "1.0"
aws-config = "0.4"
aws-sdk-ec2 = "0.4"
aws-sdk-cloudformation = "0.4"
duplicate = "0.3"
indicatif = "0.16"
ptree = "0.4"
structopt = "0.3"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
