[package]
name = "aware"
version = "0.0.13"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/imp/aware-rs"
description = "AWS Resource Explorer"

[dependencies]
anyhow = "1.0"
aws-config = "0.4"
aws-sdk-ec2 = "0.4"
aws-sdk-cloudformation = "0.4"
clap = { version = "3.0", features = ["derive"] }
duplicate = "0.3"
indicatif = "0.16"
ptree = "0.4"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
tracing-subscriber = "0.3"

[package.metadata.release]
allow-branch = ["main"]
push = true
tag = true
publish = true
verify = true
pre-release-commit-message = "Bump version to {{version}}"
tag-message = "{{version}}"
tag-name = "{{version}}"
dev-version = false
