[package]
name = "aware"
version = "0.0.3"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/imp/aware-rs"
description = "AWS Resource Explorer"

[dependencies]
aws-config = "0.0.22-alpha"
aws-sdk-ec2 = "0.0.22-alpha"
indicatif = "0.16"
ptree = "0.4"
structopt = "0.3"
tokio = { version = "1.0", features = ["full"] }
